import 'bootstrap/dist/css/bootstrap.min.css';

import Head from 'next/head'
import CardGroup from '../components/CardGroup'
import VideoGroup from '@/components/VideoGroup'
import AudioGroup from '@/components/AudioGroup'


export default function Home() {
  return (
    <>
      <Head>
        <title>Clase 11 - Props</title>
        <meta name="description" content="Generated by create next app, Cac clase 11" />
        <meta name="author" content="Cinthia M. Orona" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className='my-4'>Ejercicio Clase 11: Props entre componentes.</h1>
        <section>
          <h2 className='text-light text-center'>Cards</h2>
          <CardGroup />
        </section>
        <section>
          <h2 className='text-light text-center'>Videos</h2>
          <VideoGroup />
        </section>
        <section>
          <h2 className='text-light text-center'>Audios</h2>
          <AudioGroup />
        </section>
      </main>
    </>
  )
}
